# _config.yml
title: "Questions & Réponses"
description: "Site collaboratif"

# Force Jekyll à inclure ces dossiers
include:
  - _questions
  - _reponses

# Ne pas exclure les fichiers markdown
keep_files:
  - questions
  - reponses

# Désactive le processing des markdown
markdown: kramdown

exclude:
  - README.md
  - CONTRIBUTING.md
  - vendor
  - Gemfile
  - Gemfile.lock